# Site settings
name: step by step
email: fgdsdut@163.com
author: Guodong Fan
url: http://plusnet.cn
resume_site:
github: https://github.com/Guodongfan
baseurl:
description: null
meta_description: null
motto: null

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Guodong Fan

# Build settings
markdown: kramdown
